- type: replace
  path: /instance_groups/name=credhub-importer/jobs/name=credhub-importer/properties/credhub/seeded_credentials?
  value:
    - type: value
      name: /example/value
      value: example
    - type: json
      name: /example/json
      value: { "key": "value" }
    - type: password
      name: /example/password
      password: ((example_password))
    - type: user
      name: /example/user
      username: admin
      password: ((example_password))
    - type: certificate
      name: /example/certificate
      certificate: ((example_ssl.certificate))
      root: ((example_ssl.ca))
      private: ((example_ssl.private_key))
    - type: ssh
      name: /example/ssh
      public: ((example_ssh.public_key))
      private: ((example_ssh.private_key))
    - type: rsa
      name: /example/rsa
      public: ((example_rsa.public_key))
      private: ((example_rsa.private_key))

- type: replace
  path: /variables?/-
  value:
    name: example_password
    type: password

- type: replace
  path: /variables?/-
  value:
    name: example_ca
    type: certificate
    options:
      is_ca: true
      common_name: exampleCA

- type: replace
  path: /variables?/-
  value:
    name: example_ssl
    type: certificate
    options:
      ca: example_ca
      common_name: example.com

- type: replace
  path: /variables?/-
  value:
    name: example_ssh
    type: ssh

- type: replace
  path: /variables?/-
  value:
    name: example_rsa
    type: rsa
